services:
  mubashir-db:
    image: ankane/pgvector:latest
    container_name: mubashir-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=mubashir.105
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mubashir-net

  ollama:
    image: ollama/ollama:latest
    container_name: mubashir-ai-engine
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - mubashir-net

  dotnet-api:
    build:
      context: ./dotnet-backend
      dockerfile: Dockerfile
    container_name: mubashir-dotnet-api
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Host=mubashir-db;Database=postgres;Username=postgres;Password=mubashir.105
    depends_on:
      - mubashir-db
    networks:
      - mubashir-net

  mubashir-frontend:
    build:
      context: ./mubashir-frontend-vue
      dockerfile: Dockerfile
    container_name: mubashir-frontend
    restart: always
    networks:
      - mubashir-net
    depends_on:
      - dotnet-api

  python-ai:
    build:
      context: ./python-services
    container_name: mubashir-python-ai
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:mubashir.105@mubashir-db:5432/postgres
    depends_on:
      - mubashir-db
      - ollama
    networks:
      - mubashir-net

  nginx-gateway:
    image: nginx:latest
    container_name: mubashir-gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot_temp:/var/www/certbot:ro
    depends_on:
      - mubashir-frontend
      - dotnet-api
    networks:
      - mubashir-net

networks:
  mubashir-net:
    name: mubashir-net  # Force name without prefix
    driver: bridge

volumes:
  postgres_data:
  ollama_data:
