services:
  # Database (AI & Vector Ready)
  mubashir-db:
    image: ankane/pgvector:latest
    container_name: mubashir-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mubashir.105
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # .NET 8 API
  dotnet-api:
    build:
      context: ./dotnet-backend
      dockerfile: Dockerfile
    container_name: mubashir-dotnet-api
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=mubashir-db;Database=postgres;Username=postgres;Password=mubashir.105
    depends_on:
      - mubashir-db

  # FastAPI (AI Crawler)
  python-ai:
    build:
      context: ./python-services
    container_name: mubashir-python-ai
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:mubashir.105@mubashir-db:5432/postgres
    depends_on:
      - mubashir-db

volumes:
  postgres_data:
