name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Contabo via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 62.171.155.216
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /root/mubashir-platform
            cd /root/mubashir-platform
            # Repository management
            if [ ! -d ".git" ]; then
              git clone https://github.com/Mushi105/mubashir-platform.git .
            else
              git pull origin main
            fi
            # Puray platform ko build aur restart karna
            docker compose up --build -d
            # Cleanup old images to save space
            docker image prune -f
